import { ServiceItem } from '@domain/models/marketplace';

export const INITIAL_MARKETPLACE_ITEMS: ServiceItem[] = [
    // =========================================================================
    // 1. ROPA & MODA ESTUDIANTIL / SEGUNDA MANO (THRIFT)
    // =========================================================================
    {
      id: 'm-cloth-1',
      itemType: 'PRODUCT',
      category: 'CLOTHING_THRIFT',
      serviceType: 'Ropa & Hoodies',
      condition: 'SEMINUEVO 9/10',
      price: 'S/ 45.00',
      numericPrice: 45.00,
      originalPrice: 85.00,
      unit: '/ prenda',
      title: 'Hoodie Oversized Negro Unisex 100% Algodón con Capucha (Talla M)',
      description: 'Polera con capucha de corte oversized holgado, tela franela reactiva que no destiñe. Súper abrigadora para los salones y laboratorios de cómputo con aire acondicionado.',
      imageUrl: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?q=80&w=600&auto=format&fit=crop',
      badge: 'THRIFT / RECOMENDADO',
      location: 'Torre A - Piso 3',
      rating: 4.95,
      reviewsCount: 24,
      salesCount: 18,
      tutorName: 'Nicole Salazar',
      tutorCareer: 'Ing. Industrial',
      tutorCycle: 4,
      reputation: 97,
      tags: ['Hoodie', 'Oversized', 'Ropa', 'Thrift', 'Invierno'],
      contactMethod: 'WhatsApp: 982145781 • Entrega directa en campus Torre A',
      highlights: ['Algodón franela 100% abrigador', 'Corte moderno oversized unisex', 'Estado impecable 9/10 sin bolitas', 'Lavado y desinfectado']
    },
    {
      id: 'm-cloth-2',
      itemType: 'PRODUCT',
      category: 'CLOTHING_THRIFT',
      serviceType: 'Casacas & Abrigo',
      condition: 'SEMINUEVO 9.5/10',
      price: 'S/ 55.00',
      numericPrice: 55.00,
      originalPrice: 95.00,
      unit: '/ prenda',
      title: 'Casaca Cortaviento Impermeable con Forro Polar Térmico (Talla L)',
      description: 'Ideal para quienes tienen clases en el turno noche o viajan en transporte público tarde. Bolsillos con cierre hermético para celular y billetera.',
      imageUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?q=80&w=600&auto=format&fit=crop',
      badge: 'OFERTA',
      location: 'Torre B - Hall Principal',
      rating: 4.90,
      reviewsCount: 19,
      salesCount: 15,
      tutorName: 'Martin Ramos',
      tutorCareer: 'Ing. Software',
      tutorCycle: 6,
      reputation: 95,
      tags: ['Casaca', 'Impermeable', 'TurnoNoche', 'Ropa'],
      contactMethod: 'WhatsApp: 976332145 • Prueba de talla en campus',
      highlights: ['Material impermeable repelente al agua', 'Forro polar interior suave', 'Cierres reforzados antirrobo', 'Excelente estado 9.5/10']
    },
    {
      id: 'm-cloth-3',
      itemType: 'PRODUCT',
      category: 'CLOTHING_THRIFT',
      serviceType: 'Mochilas & Accesorios',
      condition: 'COMO NUEVA',
      price: 'S/ 48.00',
      numericPrice: 48.00,
      originalPrice: 89.00,
      unit: '/ unidad',
      title: 'Mochila Antirrobo para Laptop 15.6" con Candado TSA y Puerto USB',
      description: 'Mochila acolchada ergonómica con bolsillo oculto trasero, compartimento acolchado para laptop de hasta 15.6 pulgadas y salida para cable de carga USB.',
      imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=600&auto=format&fit=crop',
      badge: 'MÁS SOLICITADO',
      location: 'Patio Central',
      rating: 4.98,
      reviewsCount: 33,
      salesCount: 22,
      tutorName: 'Andrea Vega',
      tutorCareer: 'Ing. Sistemas',
      tutorCycle: 5,
      reputation: 99,
      tags: ['Mochila', 'Laptop', 'Antirrobo', 'Accesorios'],
      contactMethod: 'Teams: u23108892@utp.edu.pe / WhatsApp: 994512789',
      highlights: ['Compartimento acolchado para laptop', 'Material repelente a salpicaduras', 'Puerto de carga USB externo', 'Uso de solo 1 mes']
    },

    // =========================================================================
    // 2. TECNOLOGÍA & HARDWARE DE SEGUNDA MANO (SEMINUEVOS)
    // =========================================================================
    {
      id: 'm-tech2-1',
      itemType: 'PRODUCT',
      category: 'SECOND_HAND_TECH',
      serviceType: 'Periféricos Seminuevos',
      condition: 'SEMINUEVO 9/10',
      price: 'S/ 85.00',
      numericPrice: 85.00,
      originalPrice: 140.00,
      unit: '/ unidad',
      title: 'Mouse Inalámbrico Gamer Logitech G305 Lightspeed (Sensor Hero 12K)',
      description: '100% operativo sin doble click, incluye receptor USB Lightspeed original y caja. Super ligero y preciso para programar y jugar. Funciona con una sola pila AA (incluida nueva).',
      imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=600&auto=format&fit=crop',
      badge: 'TOP GADGET',
      location: 'Torre A - Laboratorio 4',
      rating: 4.94,
      reviewsCount: 29,
      salesCount: 14,
      tutorName: 'Daniel Cordova',
      tutorCareer: 'Ing. Software',
      tutorCycle: 7,
      reputation: 98,
      tags: ['Logitech', 'Mouse', 'G305', 'Inalámbrico', 'Gaming'],
      contactMethod: 'WhatsApp: 993412567 • Se prueba en el laboratorio',
      highlights: ['Sensor óptico HERO 12,000 DPI', 'Latencia ultra baja de 1ms', 'Incluye pila Duracell nueva', 'Se entrega con caja y extensor']
    },
    {
      id: 'm-tech2-2',
      itemType: 'PRODUCT',
      category: 'SECOND_HAND_TECH',
      serviceType: 'Teclados Mecánicos',
      condition: 'SEMINUEVO 9/10',
      price: 'S/ 75.00',
      numericPrice: 75.00,
      originalPrice: 130.00,
      unit: '/ unidad',
      title: 'Teclado Mecánico Redragon Kumara K552 RGB Switch Blue (TKL)',
      description: 'Teclado compacto TKL (sin pad numérico) ideal para llevar en la mochila a la universidad. Switches mecánicos Outemu Blue táctiles y audibles. Limpiado tecla por tecla con alcohol isopropílico.',
      imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=600&auto=format&fit=crop',
      badge: 'OFERTA TECH',
      location: 'Torre B - Piso 3',
      rating: 4.88,
      reviewsCount: 21,
      salesCount: 16,
      tutorName: 'Franco Huaman',
      tutorCareer: 'Ing. Sistemas',
      tutorCycle: 6,
      reputation: 94,
      tags: ['Teclado', 'Redragon', 'Mecánico', 'RGB', 'SwitchBlue'],
      contactMethod: 'Teams: u22104512@utp.edu.pe • Prueba de tipeo en vivo',
      highlights: ['Switches mecánicos táctiles', 'Iluminación RGB configurable', 'Estructura metálica resistente', 'Incluye extractor de teclas']
    },
    {
      id: 'm-tech2-3',
      itemType: 'PRODUCT',
      category: 'SECOND_HAND_TECH',
      serviceType: 'Componentes de Laptop',
      condition: 'TESTEADO 100%',
      price: 'S/ 50.00',
      numericPrice: 50.00,
      originalPrice: 85.00,
      unit: '/ unidad',
      title: 'Memoria RAM Kingston Fury Impact 8GB DDR4 3200MHz SODIMM Laptop',
      description: 'Módulo de memoria RAM para laptop. Ideal para repotenciar tu máquina de 8GB a 16GB y correr Docker, Spring Boot y Android Studio sin lentitud. Testeada con MemTest86 cero errores.',
      imageUrl: 'https://images.unsplash.com/photo-1562976540-1502c2145186?q=80&w=600&auto=format&fit=crop',
      badge: 'REPOTENCIA TU LAPTOP',
      location: 'Torre A - Laboratorio 601',
      rating: 5.0,
      reviewsCount: 15,
      salesCount: 19,
      tutorName: 'Leonardo Paz',
      tutorCareer: 'Ing. Sistemas',
      tutorCycle: 8,
      reputation: 100,
      tags: ['RAM', 'DDR4', 'Laptop', 'Upgrade', 'Kingston'],
      contactMethod: 'WhatsApp: 981140921 • Ayudo a instalarla en tu laptop',
      highlights: ['Velocidad 3200MHz CL20', 'Compatible con Intel 10th-12th gen y AMD Ryzen', 'Instalación gratuita en campus', 'Garantía personal de prueba']
    },
    {
      id: 'm-tech-3',
      itemType: 'PRODUCT',
      category: 'SECOND_HAND_TECH',
      serviceType: 'Calculadoras & Útiles',
      condition: 'SEMINUEVA 9.5/10',
      price: 'S/ 65.00',
      numericPrice: 65.00,
      originalPrice: 95.00,
      unit: '/ unidad',
      title: 'Calculadora Científica Casio FX-991LAX ClassWiz con Panel Solar',
      description: 'En excelente estado estético 9.5/10 con su tapa protectora original y celda solar funcional. Ideal para Cálculo 1, 2, 3, Física y Estadística. Resuelve matrices 4x4 e integrales.',
      imageUrl: 'https://images.unsplash.com/photo-1587145820266-a5951ee6f620?q=80&w=600&auto=format&fit=crop',
      badge: 'OFERTA ÚNICA',
      location: 'Torre A - Piso 2',
      rating: 4.88,
      reviewsCount: 16,
      salesCount: 12,
      tutorName: 'Alexis Castro',
      tutorCareer: 'Ing. Civil',
      tutorCycle: 5,
      reputation: 92,
      tags: ['Casio', 'Calculadora', 'ClassWiz', 'Cálculo', 'Física'],
      contactMethod: 'Teams: u23104992@utp.edu.pe',
      highlights: ['Resolución de matrices e integrales', 'Pantalla LCD de alta resolución', 'Batería + Celda Solar', 'Tapa rígida original']
    },

    // =========================================================================
    // 3. COMIDA, SNACKS & POSTRES CASEROS
    // =========================================================================
    {
      id: 'm-food-1',
      itemType: 'PRODUCT',
      category: 'SNACKS_FOOD',
      serviceType: 'Snacks & Postres',
      condition: 'CASERO / FRESCO',
      price: 'S/ 4.50',
      numericPrice: 4.50,
      originalPrice: 6.00,
      unit: '/ unidad',
      title: 'Brownies Artesanales de Chocolate con Fudge y Chispas',
      description: 'Hechos en casa con cacao al 70%, textura melcochosa, rellenos de fudge artesanal. Vienen en empaque individual sellado. ¡Perfectos para el break entre clases!',
      imageUrl: 'https://images.unsplash.com/photo-1515037893149-de7f840978e2?q=80&w=600&auto=format&fit=crop',
      badge: 'CASERO / FRESCO',
      location: 'Torre A - Piso 3 / Cafetería',
      rating: 4.96,
      reviewsCount: 52,
      salesCount: 88,
      tutorName: 'Sofia Ramirez',
      tutorCareer: 'Ing. Industrial',
      tutorCycle: 5,
      reputation: 98,
      tags: ['Brownies', 'Postres', 'Chocolate', 'Fresco', 'Break'],
      contactMethod: 'WhatsApp / Teams: 984512309 • Entrega inmediata en Torre A',
      highlights: ['Cacao 70% melcochoso', 'Empaque higiénico hermético', 'Entrega en 5 min en campus', 'Promo: 2 por S/ 8.00']
    },
    {
      id: 'm-food-2',
      itemType: 'PRODUCT',
      category: 'SNACKS_FOOD',
      serviceType: 'Comida de Campus',
      condition: 'DEL DÍA',
      price: 'S/ 6.00',
      numericPrice: 6.00,
      unit: '/ sandwich',
      title: 'Sandwich Triple de Pollo con Palta, Huevo y Mayonesa Casera',
      description: 'Pan de molde fresco con triple capa generosa: pechuga de pollo deshilachada, palta fuerte madura y huevo duro con receta casera. Se prepara en la mañana antes de venir a clases.',
      imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?q=80&w=600&auto=format&fit=crop',
      badge: 'ENTREGA HOY',
      location: 'Torre B - Hall Central',
      rating: 4.92,
      reviewsCount: 39,
      salesCount: 65,
      tutorName: 'Kevin Quispe',
      tutorCareer: 'Ing. Sistemas',
      tutorCycle: 4,
      reputation: 95,
      tags: ['Triples', 'Desayuno', 'PolloPalta', 'Almuerzo', 'Fresco'],
      contactMethod: 'WhatsApp: 971204891 • Pedidos hasta las 11:00 am',
      highlights: ['Ingredientes frescos del día', 'Táper ecológico incluido', 'Entrega rápida entre clases', 'Opciones con ají pollero']
    },
    {
      id: 'm-food-3',
      itemType: 'PRODUCT',
      category: 'SNACKS_FOOD',
      serviceType: 'Snacks Calientes',
      condition: 'DEL DÍA',
      price: 'S/ 5.00',
      numericPrice: 5.00,
      originalPrice: 6.50,
      unit: '/ porción',
      title: 'Empanadas de Carne al Horno con Masa Casera + Crema de Ají',
      description: 'Relleno de carne picada jugosa, cebolla caramelizada, aceituna y huevo duro. Masa crocante al horno (cero grasa de fritura). Servidas calientes desde lonchera térmica.',
      imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?q=80&w=600&auto=format&fit=crop',
      badge: 'MÁS VENDIDO',
      location: 'Patio Central / Puerta 1',
      rating: 4.88,
      reviewsCount: 44,
      salesCount: 74,
      tutorName: 'Camila Navarro',
      tutorCareer: 'Administración',
      tutorCycle: 6,
      reputation: 93,
      tags: ['Empanadas', 'Horno', 'Carne', 'AjíCasero'],
      contactMethod: 'WhatsApp: 963118945 • Entregas a partir de las 12:30 pm',
      highlights: ['Al horno sin exceso de grasa', 'Incluye crema de ají casero', 'Pack de 2 por S/ 9.00', 'Disponibles calientes']
    },

    // =========================================================================
    // 4. HARDWARE NUEVO & ACCESORIOS
    // =========================================================================
    {
      id: 'm-tech-1',
      itemType: 'PRODUCT',
      category: 'TECH_GADGETS',
      serviceType: 'Hardware & Almacenamiento',
      condition: 'NUEVO EN BLISTER',
      price: 'S/ 28.00',
      numericPrice: 28.00,
      originalPrice: 38.00,
      unit: '/ unidad',
      title: 'USB Kingston DataTraveler 64GB 3.2 con ISOs UTP + JDK & Herramientas',
      description: 'Memoria USB original de alta velocidad 3.2. Viene formateada y precargada con ISO booteable de Ubuntu 22.04 LTS / Windows 11, JDK 17 & 21, VS Code, Git, NetBeans y Docker.',
      imageUrl: 'https://images.unsplash.com/photo-1618761714958-0655d13a5935?q=80&w=600&auto=format&fit=crop',
      badge: 'STOCK HOY',
      location: 'Torre A - Laboratorio 602',
      rating: 4.95,
      reviewsCount: 61,
      salesCount: 82,
      tutorName: 'Diego Gomez',
      tutorCareer: 'Ing. Sistemas',
      tutorCycle: 6,
      reputation: 99,
      tags: ['USB', 'Kingston', 'ISOs', 'Linux', 'SoftwareUTP'],
      contactMethod: 'Teams: u22108744@utp.edu.pe / WhatsApp: 992341882',
      highlights: ['USB 3.2 Kingston Original', 'Precargado con IDEs y JDKs', 'Garantía directa de 6 meses', 'Booteo probado en laptops']
    },
    {
      id: 'm-tech-2',
      itemType: 'PRODUCT',
      category: 'TECH_GADGETS',
      serviceType: 'Adaptadores & Cables',
      condition: 'NUEVO EN CAJA',
      price: 'S/ 38.00',
      numericPrice: 38.00,
      originalPrice: 50.00,
      unit: '/ unidad',
      title: 'Adaptador HUB USB-C a HDMI 4K + 3x USB 3.0 + Carga PD 100W',
      description: 'El salvavidas para exposiciones en aulas UTP. Conecta tu laptop moderna (MacBook, Asus, Lenovo, HP) directamente a los proyectores HDMI del salón sin fallas de resolución.',
      imageUrl: 'https://images.unsplash.com/photo-1544652478-6653e09f18a2?q=80&w=600&auto=format&fit=crop',
      badge: 'POPULAR',
      location: 'Torre B - Piso 4',
      rating: 4.90,
      reviewsCount: 28,
      salesCount: 35,
      tutorName: 'Mateo Torres',
      tutorCareer: 'Ing. Software',
      tutorCycle: 7,
      reputation: 96,
      tags: ['HubUSBC', 'HDMI', 'Exposiciones', 'Laptops', 'Gadgets'],
      contactMethod: 'WhatsApp: 981140921 • Prueba en vivo antes de comprar',
      highlights: ['Salida HDMI 4K@30Hz / 1080p@60Hz', 'Carcasa de aluminio disipador', '3 puertos USB 3.0 rápidos', 'Compatible con Windows y Mac']
    },

    // =========================================================================
    // 5. IMPRESIONES & SERVICIOS EXPRESS
    // =========================================================================
    {
      id: 'm-print-1',
      itemType: 'SERVICE',
      category: 'PRINTING_SUPPLIES',
      serviceType: 'Impresiones & Copias',
      price: 'S/ 0.20',
      numericPrice: 0.20,
      unit: '/ hoja B/N',
      title: 'Impresiones Láser B/N y Color + Anillados Express Frente a Puerta 2',
      description: 'Evita las largas colas de la fotocopiadora. Envía tus PDFs, rúbricas o informes por WhatsApp con 15 minutos de anticipación y recógelos listos y anillados en la puerta del campus.',
      imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=600&auto=format&fit=crop',
      badge: 'SIN COLAS',
      location: 'Frente a Puerta 2 (Campus Lima Centro)',
      rating: 4.97,
      reviewsCount: 78,
      salesCount: 140,
      tutorName: 'Jose Mendoza',
      tutorCareer: 'Ing. Sistemas',
      tutorCycle: 7,
      reputation: 99,
      tags: ['Impresiones', 'Anillados', 'PDF', 'Puerta2', 'Express'],
      contactMethod: 'WhatsApp: 991245890 • Envía tu archivo en PDF',
      highlights: ['Impresión láser nítida 1200 DPI', 'Anillados con micas transparentes', 'Recojo en 5 minutos', 'B/N: S/ 0.20 • Color: S/ 0.60']
    },

    // =========================================================================
    // 6. TUTORÍAS ACADÉMICAS & ASESORÍAS
    // =========================================================================
    {
      id: 'm-tut-1',
      itemType: 'SERVICE',
      category: 'TUTORING',
      serviceType: 'Tutoría 1 a 1',
      price: 'S/ 25.00',
      numericPrice: 25.00,
      originalPrice: 35.00,
      unit: '/ hora',
      title: 'Preparación para PC1 y PC2: Desarrollo Web & Spring Boot 3',
      description: 'Dominio de arquitectura hexagonal, APIs REST, autenticación JWT, Angular 18 con Signals y bases de datos relacionales con resolución de rúbrica.',
      imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=600&auto=format&fit=crop',
      badge: 'TOP TUTOR',
      rating: 4.95,
      reviewsCount: 48,
      salesCount: 64,
      tutorName: 'Asesor UTP Senior',
      tutorCareer: 'Ing. Sistemas',
      tutorCycle: 7,
      courseName: 'Desarrollo Web Integrado',
      reputation: 98,
      tags: ['SpringBoot3', 'Angular', 'APF1', 'REST'],
      contactMethod: 'Microsoft Teams / Correo institucional UTP',
      highlights: ['Configuración Spring Security', 'Signals & RxJS en Angular', 'Resolución de rúbrica PC', 'Deployment en Render']
    },
    {
      id: 'm-tut-2',
      itemType: 'SERVICE',
      category: 'PROJECT_HELP',
      serviceType: 'Asesoría de Tesis / RSL',
      price: 'S/ 30.00',
      numericPrice: 30.00,
      originalPrice: 40.00,
      unit: '/ sesión',
      title: 'Metodología PRISMA y Búsquedas Bibliográficas en Scopus & IEEE',
      description: 'Estructuración de matrices PICO, ecuaciones de búsqueda booleanas complejas y redacción de RSL con citas APA 7 sin plagio.',
      imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=600&auto=format&fit=crop',
      badge: 'MÁS SOLICITADO',
      rating: 4.92,
      reviewsCount: 36,
      salesCount: 42,
      tutorName: 'Carlos Benites',
      tutorCareer: 'Ing. Sistemas',
      tutorCycle: 8,
      courseName: 'Formación para la Investigación - Sistemas',
      reputation: 95,
      tags: ['PRISMA', 'Scopus', 'IEEE', 'APA7'],
      contactMethod: 'Teams UTP: u20201452@utp.edu.pe',
      highlights: ['Filtros de exclusión PRISMA', 'Búsqueda Scopus avanzada', 'Matriz de síntesis de datos', 'Formato final de artículo']
    }
];

